# Generated by Django 3.1.7 on 2021-03-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('telephone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrf', models.CharField(blank=True, max_length=250, null=True, verbose_name='МРФ')),
                ('rf', models.CharField(blank=True, max_length=250, null=True, verbose_name='РФ')),
                ('subjectRF', models.CharField(blank=True, max_length=250, null=True, verbose_name='Субьект РФ')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('num_access_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Количество узлов доступа и связи')),
                ('status', models.CharField(blank=True, choices=[('не начат', 'не начат'), ('проблемы с допуском', 'проблемы с допуском'), ('в работе', 'в работе'), ('СМР заевершен', 'СМР заевершен'), ('принят', 'принят'), ('КС подписаны', 'КС подписаны')], max_length=250, null=True, verbose_name='Статус')),
                ('access', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=250, null=True, verbose_name='Допуск')),
                ('date_access_SMR', models.DateField(blank=True, null=True, verbose_name='Фактическая дата получения согласований/допуска на СМР')),
                ('obemy_podany', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=250, null=True, verbose_name='Объемы поданы')),
                ('ready_smr', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=250, null=True, verbose_name='СМР выполнены')),
                ('data_priemki_rtk', models.DateField(blank=True, null=True, verbose_name='Дата приемки РТК')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sl_main.contractor')),
            ],
        ),
    ]
